print("Welcome to the band name generator")
city =  input("Which city did you grow up in?\n")
pet = input("What is the name of a pet?\n")
print("Your band name could be " + city + " " + pet)
print("\n")
print("Your city choice was > " +city)
print("Your pet choice was > " +pet)
